site_name: Crush Learning Guide
site_description: Complete learning guide for the Crush AI assistant codebase
site_author: Crush Documentation Team
site_url: https://your-docs-site.com

# Source directory
docs_dir: .

# Repository
repo_name: weidonglian/crush
repo_url: https://github.com/weidonglian/crush
edit_uri: edit/learning/

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit
    - toc.follow

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: weidonglian
      repo: crush
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Overview: LEARNING_GUIDE.md
    - Analysis Summary: ANALYSIS_SUMMARY.md
  - Beginner Tutorials:
    - Overview: presentations/README.md
    - "01: First Look": presentations/beginner/01-first-look.md
    - "02: Code Structure": presentations/beginner/02-code-structure.md
    - "03: Entry Points": presentations/beginner/03-entry-points.md
    - "04: Configuration": presentations/beginner/04-configuration.md
  - Intermediate Tutorials:
    - "01: Database Architecture": presentations/intermediate/01-database-architecture.md
    - "02: AI Integration": presentations/intermediate/02-ai-integration.md
    - "03: Terminal UI": presentations/intermediate/03-terminal-ui.md
  - Advanced Tutorials:
    - "01: Performance Analysis": presentations/advanced/01-performance-analysis.md
    - "02: Extension Architecture": presentations/advanced/02-extension-architecture.md
    - "03: Advanced AI Patterns": presentations/advanced/03-advanced-ai-patterns.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/weidonglian/crush
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike

# Extra CSS
extra_css:
  - docs/stylesheets/extra.css
